# Generated by Django 4.2.6 on 2023-11-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Producto', models.IntegerField()),
                ('Id_Compra', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Precio_Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Usuario', models.IntegerField()),
                ('Precio_Total', models.IntegerField()),
            ],
        ),
    ]
